### ISSUE TITLE
Proparse error on Define buffer for temp-table

### ISSUE THREAD

**Issue by DanielBaciu** [consultingwerk/proparse#34]
Hi,

I get an error when parsing a source file which in a define buffer statement we have `TEMP-TABLE` option. Like below. 

`DEFINE BUFFER bufTtBomHeader   FOR TEMP-TABLE     ttBomHeader.`

If I drop the `TEMP-TABLE` key word, same source is parsed alright. 

Error thrown is:
org.prorefactor.refactor.RefactorException: C:\ws\dev\11.7relatief\appserver\artikel.p:1288 Storetype mismatch between proparse.dll and treeparser01: ttBomHeader 1103 1102 -> File: C:\ws\dev\11.7relatief\appserver\artikel.p Line: 1288 Column: 10 Type: BUFFER Text: BUFFER

We are using proparse.net, Version=4.1.0.1200.

Thank you for checking,
Daniel Baciu.

**Comment by mikefechner** [comment]
Closing this issue here, as there's a duplicate issue in 

https://jira.consultingwerkcloud.com/browse/SCLSUP-349
