### ISSUE TITLE
Add support for get-effective-tenant-name

### ISSUE THREAD

**Issue by mikefechner** [consultingwerk/proparse#7]
org.prorefactor.refactor.RefactorException: C:\Work_LOCAL\SmartComponents4NET\117_64\ABL\Consultingwerk\Studio\ProdictDumpHack\src\prodict\dump\_dmpdata.p:298:50: expecting THEN, found '('

antlr.MismatchedTokenException: Mismatched Token

raised by

```
    if isSuperTenant
    and user_env[32] <> "":U
    and user_env[32] <> get-effective-tenant-name("dictdb":U) then
    do:

```

**Comment by akera-io** [comment]
Added support for missing tenant related statements:

- new built in functions: 
`GET-EFFECTIVE-TENANT-NAME`
`GET-EFFECTIVE-TENANT-ID`
`SET-EFFECTIVE-TENANT`
`IS-DB-MULTI-TENANT`
`BUFFER-GROUP-ID`
`BUFFER-GROUP-NAME`
`BUFFER-PARTITION-ID`
`BUFFER-TENANT-ID`
`BUFFER-TENANT-NAME`

- new `TENANT WHERE` clause for `CREATE`/`REPOSITION`
